---
- name: Include remove old Docker packages 
  include_tasks: remove.yml

- name: Include apt update packages
  include_tasks: update.yml

- name: Include Docker configuration
  include_tasks: conf.yml

- name: Include update apt package cache (after adding Docker repository)
  include_tasks: update.yml

- name: Include Docker packages installation
  include_tasks: install.yml
