---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - snapd
    - openjdk-11-jdk
    - net-tools
    - nginx
    - git
    - curl
    - tmux
    - vim
    - python3
    - wget
    - proxychains
    - software-properties-common
    - magic-wormhole
